spring:
  profiles:
    active: blue, product
  application:
    name: blog-widget
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081